language: haskell
install:
  - "cabal --version"
  - "cabal install 'Cabal >= 1.18'"
  - "cabal install -v3 --dry-run"
  - "travis_retry cabal install --only-dependencies --force-reinstalls"
script:
  - "cabal install --jobs=1"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
